export const LANCAMENTO_REPOSITORY = Symbol('LANCAMENTO_REPOSITORY');
export const SERVICO_REPOSITORY = Symbol('SERVICO_REPOSITORY');
export const INSTITUICAO_REPOSITORY = Symbol('INSTITUICAO_REPOSITORY');
export const RECORRENCIA_REPOSITORY = Symbol('RECORRENCIA_REPOSITORY');
